// lib/dummyCourses.ts
import { CourseCardProps } from "@/components/Course/CourseCard";

export const dummyCourses: CourseCardProps[] = [
  {
    imageUrl: "https://images.unsplash.com/photo-1544531585-9847b68c8c86",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
    title: "Full Stack Web Development",
    subtitle: "Premium Course",
    instructor: "John Doe",
    price: 3499,
    originalPrice: 7000,
    discountPercent: 40,
    duration: "8 weeks",
    lessons: 32,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4f/Csharp_Logo.png",
    title: "Mastering C# & .NET",
    subtitle: "Premium Course",
    instructor: "Jane Smith",
    price: 2999,
    originalPrice: 5999,
    discountPercent: 50,
    duration: "6 weeks",
    lessons: 24,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1508780709619-79562169bc64",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
    title: "JavaScript from Scratch",
    subtitle: "Free Course",
    instructor: "Alice Johnson",
    price: 0,
    originalPrice: 1999,
    discountPercent: 100,
    duration: "4 weeks",
    lessons: 20,
    certificate: false,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1519389950473-47ba0277781c",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Logo_of_Python.svg",
    title: "Python for Beginners",
    subtitle: "Premium Course",
    instructor: "Robert Miles",
    price: 1999,
    originalPrice: 3999,
    discountPercent: 50,
    duration: "5 weeks",
    lessons: 25,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1581093588401-02d5318f5a88",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/44/SVG_Logo.svg",
    title: "SVG Animations & Graphics",
    subtitle: "Free Course",
    instructor: "Emily Carter",
    price: 0,
    originalPrice: 1499,
    discountPercent: 100,
    duration: "3 weeks",
    lessons: 12,
    certificate: false,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg",
    title: "Node.js API Development",
    subtitle: "Premium Course",
    instructor: "Mark Lee",
    price: 2799,
    originalPrice: 4999,
    discountPercent: 44,
    duration: "6 weeks",
    lessons: 28,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1504639725590-34d0984388bd",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1b/R_logo.svg",
    title: "Data Analysis with R",
    subtitle: "Premium Course",
    instructor: "Natalie Chen",
    price: 2299,
    originalPrice: 4599,
    discountPercent: 50,
    duration: "5 weeks",
    lessons: 22,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1607617601299-cf621f27fdd4",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg",
    title: "React Native for Mobile",
    subtitle: "Premium Course",
    instructor: "Carlos Ruiz",
    price: 3199,
    originalPrice: 6400,
    discountPercent: 50,
    duration: "7 weeks",
    lessons: 30,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/96/Sass_Logo_Color.svg",
    title: "CSS & Sass Masterclass",
    subtitle: "Free Course",
    instructor: "Laura Green",
    price: 0,
    originalPrice: 1999,
    discountPercent: 100,
    duration: "4 weeks",
    lessons: 18,
    certificate: false,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1537432376769-00a5b2b24f8f",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Vue.png",
    title: "Vue.js Essentials",
    subtitle: "Premium Course",
    instructor: "Daniel Park",
    price: 2499,
    originalPrice: 4999,
    discountPercent: 50,
    duration: "5 weeks",
    lessons: 20,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1573164713988-8665fc963095",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Django_logo.svg",
    title: "Django Backend Development",
    subtitle: "Premium Course",
    instructor: "Sophia Morgan",
    price: 2899,
    originalPrice: 5799,
    discountPercent: 50,
    duration: "6 weeks",
    lessons: 26,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1603791452906-c3e1c3e3e9f3",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/18/C_Programming_Language.svg",
    title: "C Programming Fundamentals",
    subtitle: "Free Course",
    instructor: "Brian Kim",
    price: 0,
    originalPrice: 1499,
    discountPercent: 100,
    duration: "3 weeks",
    lessons: 14,
    certificate: false,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg",
    title: "HTML5 & Web Design",
    subtitle: "Free Course",
    instructor: "Michelle Zhao",
    price: 0,
    originalPrice: 999,
    discountPercent: 100,
    duration: "2 weeks",
    lessons: 10,
    certificate: false,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1531497865144-0464ef8fb9e3",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Adobe_XD_CC_icon.svg",
    title: "UI/UX Design with Adobe XD",
    subtitle: "Premium Course",
    instructor: "George Brown",
    price: 1999,
    originalPrice: 3999,
    discountPercent: 50,
    duration: "4 weeks",
    lessons: 16,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1588072432836-e10032774350",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/05/Go_Logo_Blue.svg",
    title: "GoLang for Web Development",
    subtitle: "Premium Course",
    instructor: "Isabella Adams",
    price: 3299,
    originalPrice: 6599,
    discountPercent: 50,
    duration: "6 weeks",
    lessons: 24,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1585076603491-4b8b50b22587",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/10/Microsoft_Azure.svg",
    title: "Azure Cloud Basics",
    subtitle: "Free Course",
    instructor: "Ethan Walker",
    price: 0,
    originalPrice: 1999,
    discountPercent: 100,
    duration: "3 weeks",
    lessons: 12,
    certificate: false,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1611078489935-d06d6b98d9f9",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b2/Bootstrap_logo.svg",
    title: "Frontend with Bootstrap",
    subtitle: "Free Course",
    instructor: "Chloe Wilson",
    price: 0,
    originalPrice: 1499,
    discountPercent: 100,
    duration: "2 weeks",
    lessons: 8,
    certificate: false,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1590608897129-79da98d159d9",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Matlab_Logo.png",
    title: "MATLAB for Engineers",
    subtitle: "Premium Course",
    instructor: "Liam Hall",
    price: 3499,
    originalPrice: 6999,
    discountPercent: 50,
    duration: "5 weeks",
    lessons: 20,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1590608897129-79da98d159d9",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/38/Jupyter_logo.svg",
    title: "Jupyter & Data Science",
    subtitle: "Premium Course",
    instructor: "Olivia Baker",
    price: 2699,
    originalPrice: 5399,
    discountPercent: 50,
    duration: "5 weeks",
    lessons: 22,
    certificate: true,
  },
  {
    imageUrl: "https://images.unsplash.com/photo-1611078489935-d06d6b98d9f9",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png",
    title: "Advanced JavaScript Patterns",
    subtitle: "Premium Course",
    instructor: "Henry Nguyen",
    price: 2999,
    originalPrice: 5999,
    discountPercent: 50,
    duration: "6 weeks",
    lessons: 26,
    certificate: true,
  },
];
